<?php
return array (
    array(
        'varname'=>'site_name',
        'info'=>'网站名称',
        'groupid'=>1
    ),
    array(
        'varname'=>'site_logo',
        'info'=>'网站logo',
        'groupid'=>1,
        'type'=>1
    ),
    array(
        'varname'=>'seo_title',
        'info'=>'首页标题',
        'groupid'=>1
    ),
    array(
        'varname'=>'seo_keywords',
        'info'=>'首页关键词',
        'groupid'=>1
    ),
    array(
        'varname'=>'seo_description',
        'info'=>'首页描述',
        'groupid'=>1
    ),
    array(
        'varname'=>'site_copyright',
        'info'=>'版权所有',
        'groupid'=>1
    ),
    array(
        'varname'=>'site_approve',
        'info'=>'ICP备案号',
        'groupid'=>1
    ),
    array(
        'varname'=>'site_email',
        'info'=>'公司邮箱',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_telephone',
        'info'=>'公司电话',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_lxr',
        'info'=>'联系人',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_fax',
        'info'=>'公司传真',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_address',
        'info'=>'公司地址',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_tel400',
        'info'=>'全国服务热线',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_phone',
        'info'=>'手 机',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_ywzx',
        'info'=>'业务咨询',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_rszp',
        'info'=>'人事招聘',
        'groupid'=>2
    ),
    array(
        'varname'=>'site_wxqrcode',
        'info'=>'微信二维码',
        'groupid'=>2,
        'type'=>1
    ),
    array(
        'varname'=>'site_wzqrcode',
        'info'=>'网站二维码',
        'groupid'=>2,
        'type'=>1
    ),
    array(
        'varname'=>'site_400pic',
        'info'=>'400电话',
        'groupid'=>2,
        'type'=>1
    ),
    array(
        'varname'=>'wap_company',
        'info'=>'手机公司名称',
        'groupid'=>3,
        'type'=>0
    ),
    array(
        'varname'=>'wap_bdaddress',
        'info'=>'手机公司地址',
        'groupid'=>3,
        'type'=>0
    ),
    array(
        'varname'=>'wap_qrcode',
        'info'=>'首页二维码',
        'groupid'=>3,
        'type'=>1
    ),
    array(
        'varname'=>'wap_tel400',
        'info'=>'服务电话',
        'groupid'=>3,
        'type'=>0
    ),
    array(
        'varname'=>'wap_logo',
        'info'=>'网站logo',
        'groupid'=>3,
        'type'=>1
    ),
)

?>